name: typethis
description: A flutter package that aims to simplify versatile typing animation with rich text effects and other operations (reset, freeze, unfreeze).
repository: https://github.com/thecodexhub/typethis
issue_tracker: https://github.com/thecodexhub/typethis/issues
homepage: https://github.com/thecodexhub/typethis
documentation: https://github.com/thecodexhub/typethis

version: 1.0.1

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
